<h2>Angewandte Künstliche Intelligenz (<b>Pytorch</b>)</h2>

<table>
    <tr>
        <th>Matrikelnummer</th>
        <th>Name</th>
    </tr>
    <tr>
        <td>762476</td>
        <td>Simon Heiß</td>
    </tr>
</table>

<h4>Aufgaben:</h4>

In [1]:
#1. Pytorch und Numpy importieren.
import torch 
import numpy as np

torch.__version__

c:\Users\Simon Heiß\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\Simon Heiß\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\Simon Heiß\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


'2.0.1+cpu'

In [151]:
# 2. Setzen Sie den zufälligen Seed für NumPy und PyTorch beide auf "42".
np.random.seed(42)
torch.manual_seed(42)

In [152]:
# 3. Erstellen Sie ein NumPy-Array namens "arr", das 6 zufällige Ganzzahlen zwischen 0 (einschließlich) und 5 (exklusiv) enthält.

arr = np.random.randint(0, 5, size=6)

print(arr)


[3 4 2 4 4 1]


In [153]:
# 4. Erstellen Sie einen Tensor "x" aus dem obigen Array (Aufgabe 3).
x = torch.tensor(arr) 
x2 = torch.from_numpy(arr) 
print(x)
print(x2)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [154]:
# 5. Ändern Sie den dtype von x von 'int32' in 'int64‘.
x = x.to(torch.int64)
print(x, x.dtype)
x2 = x.type(torch.int64)
print(x2, x2.dtype)

tensor([3, 4, 2, 4, 4, 1]) torch.int64
tensor([3, 4, 2, 4, 4, 1]) torch.int64


In [155]:
# 6. Reshape/Forme x in einen 3x2-Tensor um (Aufgabe 4)
x = x.reshape(3, 2)
x2 = x.view(3, 2)
print("x =", x, "\n x2 = ", x2)

x = tensor([[3, 4],
        [2, 4],
        [4, 1]]) 
 x2 =  tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [156]:
# 7. Geben Sie die rechte Spalte des Tensors x zurück
right_column = x[:, 1]
print(right_column)

tensor([4, 4, 1])


In [157]:
# 8. Geben Sie einen Tensor von Quadratwerten von x zurück, ohne x zu ändern
	
# Alternative für Aufgabe 8 print(torch.pow(x, 2))
squared_x = x.square()
print(squared_x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [158]:
# 9. Erzeugen Sie einen Tensor "y" mit der gleichen Anzahl von Elementen wie x, der mit x  matrixmultipliziert werden kann. 
# Hinweis! Welche Voraussetzung muss erfüllt sein für eine Matrix-Multiplikation?


y = torch.randint(0, 5, (2, 3) , dtype= torch.int64)
print(y)



tensor([[2, 2, 1],
        [4, 1, 0]])


In [159]:
# 10. Finden Sie das Matrixprodukt von x und y.
# Alternative für Aufgabe 10 torch.mm(x,y)
result = torch.matmul(x, y)#like this the result is compareable to the squared tensor

print(result)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
